#pragma once 
// Double include guard in case #pragma once not supported
#ifndef SENSORNET_INC_TASK2_CONF_MY_APP_H_
#define SENSORNET_INC_TASK2_CONF_MY_APP_H_

#define MYFILENAMEPREFIX "MYAPP_UNIVANTW_OUTPUTFILE"
#define MYCPUFILENAME MYFILENAMEPREFIX"_CPU"
#define MYLPMFILENAME MYFILENAMEPREFIX"_LPM"
#define MYDEEPSLEEPFILENAME MYFILENAMEPREFIX"_DEEP_LPM"
#define MYTXFILENAME MYFILENAMEPREFIX"_TX"
#define MYRXFILENAME MYFILENAMEPREFIX"_RX"
#define MYTICKSFILENAME MYFILENAMEPREFIX"_TIME_TICKS"
#define MYSECONDSFILENAME MYFILENAMEPREFIX"_TIME_SECOND"

#endif